import duckdb

schema_empresa = pa.DataFrameSchema({
    "CNPJ BÁSICO": 'BIGINT',
    "RAZÃO SOCIAL / NOME EMPRESARIAL": 'VARCHAR',
    "NATUREZA JURÍDICA": 'VARCHAR',
    "QUALIFICAÇÃO DO RESPONSÁVEL": 'VARCHAR',
    "CAPITAL SOCIAL DA EMPRESA": 'VARCHAR',
    "PORTE DA EMPRESA": 'VARCHAR',
    "ENTE FEDERATIVO RESPONSÁVEL": 'VARCHAR'
})