import duckdb

DATABASE_NAME = 'gov_cnpj.db'


con = duckdb.connect(DATABASE_NAME)
con.sql("""
        
CREATE TABLE cnaes (
                CNAE_FISCAL_PRINCIPAL VARCHAR NOT NULL,
                DESCRICAO VARCHAR NOT NULL,
                CONSTRAINT cnaes_pk PRIMARY KEY (CNAE_FISCAL_PRINCIPAL)
);


CREATE TABLE natureza_juridica (
                NATUREZA_JURIDICA VARCHAR NOT NULL,
                DESCRICAO VARCHAR NOT NULL,
                CONSTRAINT natureza_juridica_pk PRIMARY KEY (NATUREZA_JURIDICA)
);


CREATE TABLE qualificacao_socio (
                QUALIFICACAO_DO_SOCIO VARCHAR NOT NULL,
                DESCRICAO VARCHAR NOT NULL,
                CONSTRAINT qualificacao_socio_pk PRIMARY KEY (QUALIFICACAO_DO_SOCIO)
);


CREATE TABLE municipios (
                MUNICIPIO VARCHAR NOT NULL,
                DESCRICAO VARCHAR NOT NULL,
                CONSTRAINT municipios_pk PRIMARY KEY (MUNICIPIO)
);


CREATE TABLE paises (
                PAIS VARCHAR NOT NULL,
                DESCRICAO VARCHAR NOT NULL,
                CONSTRAINT paises_pk PRIMARY KEY (PAIS)
);


CREATE TABLE empresas (
                CNPJ_BASICO VARCHAR NOT NULL,
                RAZAO_SOCIAL_NOME_EMPRESARIAL VARCHAR NOT NULL,
                NATUREZA_JURIDICA VARCHAR NOT NULL,
                QUALIFICACAO_DO_RESPONSAVEL VARCHAR NOT NULL,
                CAPITAL_SOCIAL_DA_EMPRESA REAL NOT NULL,
                PORTE_DA_EMPRESA VARCHAR NOT NULL,
                ENTE_FEDERATIVO_RESPONSAVEL VARCHAR,
                CONSTRAINT empresas_pk PRIMARY KEY (CNPJ_BASICO)
);


CREATE TABLE socios (
                CNPJ_BASICO VARCHAR NOT NULL,
                IDENTIFICADOR_DE_SOCIO VARCHAR NOT NULL,
                NOME_DO_SOCIO_NO_CASO_PF_OU_RAZAO_SOCIAL_NO_CASO_PJ VARCHAR NOT NULL,
                CNPJ_CPF_DO_SOCIO VARCHAR NOT NULL,
                QUALIFICACAO_DO_SOCIO VARCHAR NOT NULL,
                DATA_DE_ENTRADA_SOCIEDADE DATE NOT NULL,
                PAIS VARCHAR NOT NULL,
                REPRESENTANTE_LEGAL VARCHAR NOT NULL,
                NOME_DO_REPRESENTANTE VARCHAR NOT NULL,
                QUALIFICACAO_DO_REPRESENTANTE_LEGAL VARCHAR NOT NULL,
                FAIXA_ETARIA VARCHAR NOT NULL,
                CONSTRAINT socios_pk PRIMARY KEY (CNPJ_BASICO, IDENTIFICADOR_DE_SOCIO)
);


CREATE TABLE simples (
                CNPJ_BASICO VARCHAR NOT NULL,
                OPCAO_PELO_SIMPLES VARCHAR NOT NULL,
                DATA_DE_OPCAO_PELO_SIMPLES DATE,
                DATA_DE_EXCLUSAO_DO_SIMPLES VARCHAR,
                OPCAO_PELO_MEI VARCHAR,
                DATA_DE_OPCAO_PELO_MEI DATE,
                DATA_DE_EXCLUSAO_DO_MEI DATE,
                CONSTRAINT simples_pk PRIMARY KEY (CNPJ_BASICO, OPCAO_PELO_SIMPLES)
);


CREATE TABLE estabelecimentos (
                CNPJ_BASICO VARCHAR NOT NULL,
                CNPJ_ORDEM VARCHAR NOT NULL,
                CNPJ_DV VARCHAR NOT NULL,
                IDENTIFICADOR_MATRIZ_FILIAL VARCHAR NOT NULL,
                NOME_FANTASIA VARCHAR NOT NULL,
                SITUACAO_CADASTRAL VARCHAR NOT NULL,
                DATA_SITUACAO_CADASTRAL DATE NOT NULL,
                MOTIVO_SITUACAO_CADASTRAL VARCHAR NOT NULL,
                NOME_DA_CIDADE_NO_EXTERIOR VARCHAR NOT NULL,
                PAIS VARCHAR NOT NULL,
                DATA_DE_INICIO_ATIVIDADE DATE NOT NULL,
                CNAE_FISCAL_PRINCIPAL VARCHAR NOT NULL,
                CNAE_FISCAL_SECUNDARIA VARCHAR NOT NULL,
                TIPO_DE_LOGRADOURO VARCHAR NOT NULL,
                LOGRADOURO VARCHAR NOT NULL,
                NUMERO VARCHAR NOT NULL,
                COMPLEMENTO VARCHAR NOT NULL,
                BAIRRO VARCHAR NOT NULL,
                CEP VARCHAR NOT NULL,
                UF VARCHAR NOT NULL,
                MUNICIPIO VARCHAR NOT NULL,
                DDD_1 VARCHAR NOT NULL,
                TELEFONE_1 VARCHAR NOT NULL,
                DDD_2 VARCHAR NOT NULL,
                TELEFONE_2 VARCHAR NOT NULL,
                DDD_DO_FAX VARCHAR NOT NULL,
                FAX VARCHAR NOT NULL,
                CORREIO_ELETRONICO VARCHAR NOT NULL,
                SITUACAO_ESPECIAL VARCHAR NOT NULL,
                DATA_DA_SITUACAO_ESPECIAL DATE NOT NULL,
                CONSTRAINT estabelecimentos_pk PRIMARY KEY (CNPJ_BASICO, CNPJ_ORDEM, CNPJ_DV, IDENTIFICADOR_MATRIZ_FILIAL)
);
""")